import { mkdirSync, writeFileSync, cpSync, readFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { copyRuntimeSkillsTo } from "./assets.js";
import { checkbox, confirm } from "@inquirer/prompts";
import chalk from "chalk";
import ora from "ora";
import {
  ALL_PLATFORMS,
  detectInstalledPlatforms,
  isPlatform,
  readMeta,
  RUNTIME_SKILL_DIRS,
  writeMeta,
  type Platform,
  type PlatformEntry,
} from "./meta.js";

const AGGREGATION_DIRS = [
  "requirements",
  "roadmap",
  "features",
  "issues",
  "refactors",
  "brainstorms",
  "compound",
];

const ARCHITECTURE_TEMPLATE = `# 架构总入口

> 状态：骨架（待填充）
> 创建日期：${new Date().toISOString().slice(0, 10)}

## 1. 项目简介

## 2. 核心概念 / 术语表

## 3. 子系统 / 模块索引

## 4. 关键架构决定

## 5. 已知约束 / 硬边界
`;

const ATTENTION_TEMPLATE = `# Attention

本文件是 kflow 执行类技能启动前读取的短提醒清单。路由类技能只检查它是否存在；真正动手改代码 / 写文档前再读全文。

原则：一条一行，最多 50 条有效项目。详细背景请沉淀到 compound / architecture / requirement / feature / issue 文档，这里只保留短提醒和链接。

## 项目碎片知识

<!-- k-note managed: 用 k-note 维护，新条目按下面分节追加 -->

### 编译与构建

### 运行与本地起服务

### 测试

### 命令与脚本陷阱

### 路径与目录约定

### 环境变量与凭证

### 其他
`;

function generateAgentsMd(platforms: string[]): string {
  if (platforms.length === 0) return AGENTS_NO_PLATFORM;
  const list = platforms.map((p) => `- **${p}**`).join("\n");
  return `# AGENTS

kflow — AI coding workflow skill pack for serious engineering. Generated by kflow CLI.

## Installed Platforms

${list}

## Quick Start

Use \`/k-flow\` as the Skill Workflow entrypoint. The agent will route you to the right sub-skill.

\`\`\`
/k-flow    # Start here
\`\`\`

Runtime skills are installed in \`.agents/skills/\`.
`;
}

const AGENTS_NO_PLATFORM = `# AGENTS

kflow — AI coding workflow skill pack for serious engineering. Generated by kflow CLI.

## Installed Platforms

_(none — run \`kflow init\` again to add platforms)_

## Quick Start

Use \`/k-flow\` as the Skill Workflow entrypoint. The agent will route you to the right sub-skill.

\`\`\`
/k-flow    # Start here
\`\`\`

Runtime skills are installed in \`.agents/skills/\`.
`;

/** Copy a single platform's integration files from the package into cwd. */
function installPlatform(pkgRoot: string, cwd: string, platform: Platform): void {
  const src = join(pkgRoot, "platforms", platform);
  cpSync(src, cwd, { recursive: true });
}

/** Ensure .kflow dirs and templates exist (idempotent). */
function ensureKflowDirs(cwd: string, pkgRoot: string): void {
  const kflowDir = join(cwd, ".kflow");
  mkdirSync(kflowDir, { recursive: true });

  for (const dir of AGGREGATION_DIRS) {
    mkdirSync(join(kflowDir, dir), { recursive: true });
  }

  const archDir = join(kflowDir, "architecture");
  mkdirSync(archDir, { recursive: true });
  const archFile = join(archDir, "ARCHITECTURE.md");
  if (!existsSync(archFile)) {
    writeFileSync(archFile, ARCHITECTURE_TEMPLATE);
  }

  const attnFile = join(kflowDir, "attention.md");
  if (!existsSync(attnFile)) {
    writeFileSync(attnFile, ATTENTION_TEMPLATE);
  }

  // Templates (overwrite to stay current)
  const srcTemplates = join(pkgRoot, "templates");
  const dstRef = join(kflowDir, "reference");
  cpSync(srcTemplates, dstRef, { recursive: true });

  // Tools (overwrite to stay current)
  const srcTools = join(pkgRoot, "tools");
  const dstTools = join(kflowDir, "tools");
  cpSync(srcTools, dstTools, { recursive: true });
}

function pkgVersion(pkgRoot: string): string {
  try {
    const p = JSON.parse(readFileSync(join(pkgRoot, "package.json"), "utf-8"));
    return (p as { version?: string }).version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function printCompactBrandMark(): void {
  console.log("kflow · AI coding workflow skill pack");
  console.log("");
}

function printFullBrandMark(): void {
  console.log(chalk.bold("╭──────────────────────────────────────────────────────╮"));
  console.log(chalk.bold("│") + "  kflow · AI coding workflow skill pack              " + chalk.bold("│"));
  console.log(chalk.bold("│") + "  orchestrate the software lifecycle                 " + chalk.bold("│"));
  console.log(chalk.bold("│") + "  with humans in the loop                            " + chalk.bold("│"));
  console.log(chalk.bold("╰──────────────────────────────────────────────────────╯"));
  console.log("");
}

export async function run(argv: string[]): Promise<void> {
  const cwd = process.cwd();
  const pkgRoot = resolve(import.meta.dirname, "..", "..");

  // Parse --platform and --no-save flags
  const platformArg = argv.find((a) => a.startsWith("--platform="));
  const platformList = platformArg?.replace("--platform=", "");
  const noSave = argv.includes("--no-save");

  // Detect already-installed platforms
  const meta = readMeta(cwd);
  const fileInstalled = detectInstalledPlatforms(cwd);
  const metaInstalled = meta?.platforms?.map((e) => e.name) ?? [];
  const alreadyInstalled = [...new Set([...fileInstalled, ...metaInstalled])];

  let selected: Platform[];

  // ── Deterministic path (--platform flag) ─────────────────────────────
  if (platformList) {
    printCompactBrandMark();
    const names = platformList.split(",").map((s) => s.trim()).filter(Boolean);
    for (const n of names) {
      if (!isPlatform(n)) {
        console.error(
          chalk.red(`kflow init: unsupported platform '${n}'. Supported: ${ALL_PLATFORMS.join(", ")}`)
        );
        process.exit(1);
      }
    }
    selected = [...new Set(names)] as Platform[];

    // Filter out already-installed
    const newPlatforms = selected.filter((p) => !alreadyInstalled.includes(p));
    if (newPlatforms.length === 0) {
      console.log(chalk.yellow("All selected platforms are already installed."));
      process.exit(0);
    }
    selected = newPlatforms;
  } else {
    // ── Interactive picker ─────────────────────────────────────────────

    printFullBrandMark();

    // Sort: installed platforms first, then remaining alphabetically
    const remaining = ALL_PLATFORMS.filter((p) => !alreadyInstalled.includes(p));
    const choices = [
      ...alreadyInstalled.map((p) => ({
        name: `${p} ${chalk.dim("(already installed)")}`,
        value: p,
        checked: false,
        disabled: true,
      })),
      ...remaining.map((p) => ({
        name: p,
        value: p,
        checked: p === "codex" && !alreadyInstalled.includes("codex"),
      })),
    ];

    const installable = remaining.length > 0;
    if (!installable) {
      console.log(chalk.green("All platforms are already installed."));
      process.exit(0);
    }

    // No-package.json warning
    if (!existsSync(join(cwd, "package.json"))) {
      const proceed = await confirm({
        message: chalk.yellow(
          "No package.json found. kflow will not be saved as a devDependency. Continue?"
        ),
        default: true,
      });
      if (!proceed) {
        console.log(chalk.dim("Aborted."));
        process.exit(0);
      }
    }

    selected = await checkbox({
      message: "Select platforms to install:",
      choices,
      pageSize: 10,
    }) as Platform[];

    if (selected.length === 0) {
      console.log(chalk.dim("No platforms selected. Aborted."));
      process.exit(0);
    }
  }

  // ── Install ──────────────────────────────────────────────────────────

  // 1. Ensure .kflow skeletons
  ensureKflowDirs(cwd, pkgRoot);

  // 2. Install skills into each platform's runtime skill directory (deduped)
  const dirs = [...new Set(selected.map((p) => RUNTIME_SKILL_DIRS[p]))];
  const spinner = ora("Installing kflow skill assets…").start();
  for (const dir of dirs) {
    copyRuntimeSkillsTo(pkgRoot, cwd, dir);
  }
  spinner.succeed("kflow skill assets installed.");

  // 3. Install selected platforms
  for (const p of selected) {
    spinner.start(`Installing ${p} integration…`);
    installPlatform(pkgRoot, cwd, p);
    spinner.succeed(`${p} integration installed.`);
  }

  // 4. Write / update meta.json
  const now = new Date().toISOString();
  const existingEntries = meta?.platforms ?? [];
  const newEntries: PlatformEntry[] = selected.map((name) => ({ name, installedAt: now }));
  // Merge: keep existing entries not being re-added + new entries
  const merged: PlatformEntry[] = [
    ...existingEntries.filter((e) => !selected.includes(e.name as Platform)),
    ...newEntries,
  ];
  writeMeta(cwd, {
    platforms: merged,
    version: pkgVersion(pkgRoot),
  });

  // 5. Write AGENTS.md with all installed platforms
  const allInstalled = merged.map((e) => e.name);
  writeFileSync(join(cwd, "AGENTS.md"), generateAgentsMd(allInstalled));

  // 6. Success output
  console.log("");
  if (alreadyInstalled.length > 0) {
    console.log(chalk.dim(`Previously installed: ${alreadyInstalled.join(", ")}`));
  }
  console.log(chalk.green(`kflow initialized with: ${selected.join(", ")}`));
  console.log("Use /k-flow as the Skill Workflow entrypoint in your Agent Runtime.");

  // 7. Save kflow as devDependency
  if (noSave) return;
  const targetPkgPath = join(cwd, "package.json");
  if (existsSync(targetPkgPath)) {
    const targetPkg = JSON.parse(readFileSync(targetPkgPath, "utf-8"));
    targetPkg.devDependencies ??= {};
    targetPkg.devDependencies["kflow"] = "*";
    writeFileSync(targetPkgPath, JSON.stringify(targetPkg, null, 2) + "\n");
  }
}
