import { mkdirSync, writeFileSync, cpSync, readFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { copyRuntimeSkills } from "./assets.js";

const AGGREGATION_DIRS = [
  "requirements",
  "roadmap",
  "features",
  "issues",
  "refactors",
  "brainstorms",
  "compound",
];

const ARCHITECTURE_TEMPLATE = `# 架构总入口

> 状态：骨架（待填充）
> 创建日期：${new Date().toISOString().slice(0, 10)}

## 1. 项目简介

## 2. 核心概念 / 术语表

## 3. 子系统 / 模块索引

## 4. 关键架构决定

## 5. 已知约束 / 硬边界
`;

const ATTENTION_TEMPLATE = `# Attention

本文件是 kflow 执行类技能启动前读取的短提醒清单。路由类技能只检查它是否存在；真正动手改代码 / 写文档前再读全文。

原则：一条一行，最多 50 条有效项目。详细背景请沉淀到 compound / architecture / requirement / feature / issue 文档，这里只保留短提醒和链接。

## 项目碎片知识

<!-- k-note managed: 用 k-note 维护，新条目按下面分节追加 -->

### 编译与构建

### 运行与本地起服务

### 测试

### 命令与脚本陷阱

### 路径与目录约定

### 环境变量与凭证

### 其他
`;

const AGENTS_TEMPLATE = `# AGENTS

kflow — AI coding workflow skill pack for serious engineering. Generated by kflow CLI.

## Default Platform

**Codex** — kflow is installed for Codex by default.

## Quick Start

Use \`/k-flow\` as the Skill Workflow entrypoint. The agent will route you to the right sub-skill.

\`\`\`
/k-flow    # Start here
\`\`\`

Runtime skills are installed in \`.agents/skills/\`.
`;

export function run(argv: string[]): void {
  const cwd = process.cwd();
  const kflowDir = join(cwd, ".kflow");

  // Package root: dist/commands/init.js → ../../ → pkg root
  const pkgRoot = resolve(import.meta.dirname, "..", "..");

  mkdirSync(kflowDir, { recursive: true });

  // Aggregation dirs
  for (const dir of AGGREGATION_DIRS) {
    const dirPath = join(kflowDir, dir);
    mkdirSync(dirPath, { recursive: true });
  }

  // architecture/ dir + ARCHITECTURE.md placeholder
  const archDir = join(kflowDir, "architecture");
  mkdirSync(archDir, { recursive: true });
  writeFileSync(
    join(archDir, "ARCHITECTURE.md"),
    ARCHITECTURE_TEMPLATE
  );

  // attention.md minimal template
  writeFileSync(join(kflowDir, "attention.md"), ATTENTION_TEMPLATE);

  // Copy templates/ → .kflow/reference/
  const srcTemplates = join(pkgRoot, "templates");
  const dstRef = join(kflowDir, "reference");
  cpSync(srcTemplates, dstRef, { recursive: true });

  // Copy tools/ → .kflow/tools/
  const srcTools = join(pkgRoot, "tools");
  const dstTools = join(kflowDir, "tools");
  cpSync(srcTools, dstTools, { recursive: true });

  // Copy skills into the universal runtime discovery path.
  copyRuntimeSkills(pkgRoot, cwd);

  // AGENTS.md — simplified skeleton with Codex default platform marker
  writeFileSync(join(cwd, "AGENTS.md"), AGENTS_TEMPLATE);

  console.log("kflow initialized. Use /k-flow as the Skill Workflow entrypoint in your Agent Runtime.");

  // Save kflow as devDependency (unless --no-save)
  const noSave = argv.includes("--no-save");
  if (noSave) {
    return;
  }

  const targetPkgPath = join(cwd, "package.json");
  if (existsSync(targetPkgPath)) {
    const targetPkg = JSON.parse(readFileSync(targetPkgPath, "utf-8"));
    targetPkg.devDependencies ??= {};
    targetPkg.devDependencies["kflow"] = "*";
    writeFileSync(targetPkgPath, JSON.stringify(targetPkg, null, 2) + "\n");
  }
}
