import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PLATFORM_REGISTRY, type Platform } from "../project-onboarding/lifecycle.js";

export type { Platform } from "../project-onboarding/lifecycle.js";

export interface PlatformEntry {
  name: string;
  installedAt: string;
}

export interface MetaJson {
  platforms: PlatformEntry[];
  version: string;
}

/** Read .kflow/meta.json; returns null if absent or malformed. */
export function readMeta(cwd: string): MetaJson | null {
  const path = join(cwd, ".kflow", "meta.json");
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as MetaJson;
  } catch {
    return null;
  }
}

/** Write or overwrite .kflow/meta.json. */
export function writeMeta(cwd: string, meta: MetaJson): void {
  const path = join(cwd, ".kflow", "meta.json");
  writeFileSync(path, JSON.stringify(meta, null, 2) + "\n");
}

const SUPPORTED = Object.keys(PLATFORM_REGISTRY) as Platform[];

export function isPlatform(name: string): name is Platform {
  return (SUPPORTED as readonly string[]).includes(name);
}

export const ALL_PLATFORMS: readonly Platform[] = SUPPORTED;

/** Platform → runtime skill directory mapping. */
export const RUNTIME_SKILL_DIRS: Record<Platform, string> = Object.fromEntries(
  ALL_PLATFORMS.map((platform) => [platform, PLATFORM_REGISTRY[platform].runtimeSkillDirectory]),
) as Record<Platform, string>;

/** Heuristic: which platforms appear to be installed (files exist + kflow marker). */
export function detectInstalledPlatforms(cwd: string): Platform[] {
  const installed: Platform[] = [];
  const MARKER = "Generated by kflow";
  for (const p of ALL_PLATFORMS) {
    const entryFile = p === "claude" ? "CLAUDE.md" : "AGENTS.md";
    const entry = join(cwd, entryFile);
    if (existsSync(entry)) {
      // For AGENTS.md (shared by Codex/Cursor/OpenCode), check if meta.json
      // records the platform since the file is shared.
      if (entryFile === "AGENTS.md") {
        // Only for file-based fallback: check if meta records these platforms
        const meta = readMeta(cwd);
        if (meta) {
          // Trust meta.json: return only what it records
          continue; // handled below
        }
        // No meta.json: AGENTS.md alone can't distinguish codex/cursor/opencode
        try {
          const content = readFileSync(entry, "utf-8");
          if (content.includes(MARKER) || content.includes("kflow")) {
            installed.push(p);
          }
        } catch {}
      } else {
        // CLAUDE.md is unique to claude
        try {
          const content = readFileSync(entry, "utf-8");
          if (content.includes(MARKER) || content.includes("kflow")) {
            installed.push(p);
          }
        } catch {}
      }
    }
  }

  // If meta.json exists, trust it as the authoritative source
  const meta = readMeta(cwd);
  if (meta) {
    return meta.platforms.map((e) => e.name as Platform).filter((p) => ALL_PLATFORMS.includes(p));
  }

  return [...new Set(installed)];
}
