import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const PLATFORM_REGISTRY = {
  claude: {
    integrationTemplate: "platforms/claude",
    entryFile: "CLAUDE.md",
    runtimeSkillDirectory: ".claude/skills",
  },
  codex: {
    integrationTemplate: "platforms/codex",
    entryFile: "AGENTS.md",
    runtimeSkillDirectory: ".agents/skills",
  },
  cursor: {
    integrationTemplate: "platforms/cursor",
    entryFile: "AGENTS.md",
    runtimeSkillDirectory: ".agents/skills",
  },
  opencode: {
    integrationTemplate: "platforms/opencode",
    entryFile: "AGENTS.md",
    runtimeSkillDirectory: ".agents/skills",
  },
} as const;

export type Platform = keyof typeof PLATFORM_REGISTRY;

export interface ProjectFilesystem {
  exists(path: string): boolean;
  readText(path: string): string;
}

export interface ProjectOnboardingLifecycle {
  inspect(cwd: string): ProjectOnboardingInspection;
}

const nodeFilesystem: ProjectFilesystem = {
  exists: existsSync,
  readText: (path) => readFileSync(path, "utf-8"),
};

export interface AuthoritativeInstallationState {
  kind: "authoritative";
  platforms: Platform[];
  version: string;
}

export interface MalformedInstallationState {
  kind: "malformed";
  reason: "invalid-json";
}

export interface InvalidInstallationState {
  kind: "invalid";
  reason: "invalid-shape";
}

export interface InferredInstallationState {
  kind: "inferred";
  platforms: Platform[];
}

export interface AbsentInstallationState {
  kind: "absent";
}

export type InstallationState =
  | AuthoritativeInstallationState
  | MalformedInstallationState
  | InvalidInstallationState
  | InferredInstallationState
  | AbsentInstallationState;

export interface ProjectOnboardingInspection {
  installationState: InstallationState;
  health: ProjectOnboardingHealth;
}

export interface ProjectOnboardingHealth {
  structure: "healthy" | "missing";
  installedPlatforms: "healthy" | "missing";
  projectCliDependency: "healthy" | "missing";
  installationEvidence: "consistent" | "missing" | "unexpected" | "not-applicable";
}

export function createProjectOnboardingLifecycle(
  filesystem: ProjectFilesystem,
): ProjectOnboardingLifecycle {
  return { inspect: (cwd) => inspect(cwd, filesystem) };
}

const defaultLifecycle = createProjectOnboardingLifecycle(nodeFilesystem);

export function inspectProjectOnboarding(cwd: string): ProjectOnboardingInspection {
  return defaultLifecycle.inspect(cwd);
}

function inspect(cwd: string, filesystem: ProjectFilesystem): ProjectOnboardingInspection {
  const metaPath = join(cwd, ".kflow", "meta.json");
  if (!filesystem.exists(metaPath)) {
    return inspection(cwd, inferLegacyInstallationState(cwd, filesystem), filesystem);
  }
  let text: string;
  try {
    text = filesystem.readText(metaPath);
  } catch {
    return inspection(cwd, { kind: "malformed", reason: "invalid-json" }, filesystem);
  }
  let data: unknown;
  try {
    data = JSON.parse(text);
  } catch {
    return inspection(cwd, { kind: "malformed", reason: "invalid-json" }, filesystem);
  }
  if (!isPersistedInstallationState(data)) {
    return inspection(cwd, { kind: "invalid", reason: "invalid-shape" }, filesystem);
  }

  return inspection(cwd, {
    kind: "authoritative",
    platforms: data.platforms.map((entry) => entry.name),
    version: data.version,
  }, filesystem);
}

function inspection(
  cwd: string,
  installationState: InstallationState,
  filesystem: ProjectFilesystem,
): ProjectOnboardingInspection {
  const structure = filesystem.exists(join(cwd, ".kflow"))
    && filesystem.exists(join(cwd, ".kflow", "reference"))
    && filesystem.exists(join(cwd, ".kflow", "tools"));
  const installedPlatforms = (installationState.kind === "authoritative"
    || installationState.kind === "inferred")
    && installationState.platforms.length > 0;

  let projectCliDependency = false;
  try {
    const pkg = JSON.parse(filesystem.readText(join(cwd, "package.json"))) as {
      devDependencies?: Record<string, unknown>;
    };
    projectCliDependency = Boolean(pkg.devDependencies?.kflow);
  } catch {
    projectCliDependency = false;
  }

  const installationEvidence = compareInstallationEvidence(cwd, installationState, filesystem);

  return {
    installationState,
    health: {
      structure: structure ? "healthy" : "missing",
      installedPlatforms: installedPlatforms ? "healthy" : "missing",
      projectCliDependency: projectCliDependency ? "healthy" : "missing",
      installationEvidence,
    },
  };
}

function inferLegacyInstallationState(
  cwd: string,
  filesystem: ProjectFilesystem,
): InferredInstallationState | AbsentInstallationState {
  const platforms: Platform[] = [];
  const marker = "Generated by kflow";
  const hasKflowEntry = (file: string): boolean => {
    const path = join(cwd, file);
    if (!filesystem.exists(path)) return false;
    try {
      return filesystem.readText(path).includes(marker);
    } catch {
      return false;
    }
  };

  if (hasKflowEntry("CLAUDE.md")) platforms.push("claude");
  if (hasKflowEntry("AGENTS.md")) platforms.push("codex", "cursor", "opencode");
  return platforms.length > 0 ? { kind: "inferred", platforms } : { kind: "absent" };
}

function compareInstallationEvidence(
  cwd: string,
  state: InstallationState,
  filesystem: ProjectFilesystem,
): ProjectOnboardingHealth["installationEvidence"] {
  if (state.kind !== "authoritative") return "not-applicable";
  const marker = "Generated by kflow";
  const isKflowEntry = (file: string): boolean => {
    const path = join(cwd, file);
    if (!filesystem.exists(path)) return false;
    try {
      return filesystem.readText(path).includes(marker);
    } catch {
      return false;
    }
  };
  const expectedFiles = new Set(state.platforms.map((platform) => PLATFORM_REGISTRY[platform].entryFile));
  const knownFiles = new Set(Object.values(PLATFORM_REGISTRY).map((platform) => platform.entryFile));
  const presentFiles = [...knownFiles].filter(isKflowEntry);
  if ([...expectedFiles].some((file) => !presentFiles.includes(file))) return "missing";
  if (presentFiles.some((file) => !expectedFiles.has(file))) return "unexpected";
  return "consistent";
}

function isPersistedInstallationState(
  value: unknown,
): value is { platforms: Array<{ name: Platform; installedAt: string }>; version: string } {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Record<string, unknown>;
  if (typeof candidate.version !== "string" || candidate.version.length === 0 || !Array.isArray(candidate.platforms)) {
    return false;
  }
  const names = new Set<string>();
  return candidate.platforms.every((entry) => {
    if (typeof entry !== "object" || entry === null) return false;
    const platform = entry as Record<string, unknown>;
    const valid = typeof platform.name === "string"
      && platform.name in PLATFORM_REGISTRY
      && typeof platform.installedAt === "string"
      && platform.installedAt.length > 0;
    if (!valid || names.has(platform.name as string)) return false;
    names.add(platform.name as string);
    return true;
  });
}
