import { afterEach, describe, expect, it } from "vitest";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tempProject } from "../cli-helpers/temp";
import {
  createProjectOnboardingLifecycle,
  inspectProjectOnboarding,
} from "../../src/project-onboarding/lifecycle";

const projects: string[] = [];

function project(): string {
  const cwd = tempProject();
  projects.push(cwd);
  return cwd;
}

function writeMeta(cwd: string, value: unknown): void {
  mkdirSync(join(cwd, ".kflow"), { recursive: true });
  writeFileSync(join(cwd, ".kflow/meta.json"), JSON.stringify(value));
}

afterEach(() => {
  for (const cwd of projects.splice(0)) {
    rmSync(cwd, { recursive: true, force: true });
  }
});

describe("Project Onboarding lifecycle", () => {
  it("treats valid persisted Installation State as authoritative over entry files", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [{ name: "claude", installedAt: "2026-07-13T00:00:00.000Z" }],
      version: "2.0.0",
    });
    writeFileSync(join(cwd, "AGENTS.md"), "Generated by kflow\n");

    const result = inspectProjectOnboarding(cwd);

    expect(result.installationState).toEqual({
      kind: "authoritative",
      platforms: ["claude"],
      version: "2.0.0",
    });
  });

  it("distinguishes malformed persisted Installation State from absent state", () => {
    const cwd = project();
    mkdirSync(join(cwd, ".kflow"), { recursive: true });
    writeFileSync(join(cwd, ".kflow/meta.json"), "{not-json");

    const result = inspectProjectOnboarding(cwd);

    expect(result.installationState).toEqual({
      kind: "malformed",
      reason: "invalid-json",
    });
  });

  it("reports structurally invalid persisted Installation State", () => {
    const cwd = project();
    writeMeta(cwd, { platforms: [{ name: "unknown" }], version: 2 });

    expect(inspectProjectOnboarding(cwd).installationState).toEqual({
      kind: "invalid",
      reason: "invalid-shape",
    });
  });

  it("reports absent Installation State when no persisted or legacy evidence exists", () => {
    expect(inspectProjectOnboarding(project()).installationState).toEqual({ kind: "absent" });
  });

  it("infers legacy Installation State only when persisted state is absent", () => {
    const cwd = project();
    writeFileSync(join(cwd, "CLAUDE.md"), "Generated by kflow\n");

    expect(inspectProjectOnboarding(cwd).installationState).toEqual({
      kind: "inferred",
      platforms: ["claude"],
    });
  });

  it("reports all candidates represented by the shared legacy entry file", () => {
    const cwd = project();
    writeFileSync(join(cwd, "AGENTS.md"), "Generated by kflow\n");

    expect(inspectProjectOnboarding(cwd).installationState).toEqual({
      kind: "inferred",
      platforms: ["codex", "cursor", "opencode"],
    });
  });

  it("returns structured health facts from the same Installation State", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [{ name: "claude", installedAt: "2026-07-13T00:00:00.000Z" }],
      version: "2.0.0",
    });
    mkdirSync(join(cwd, ".kflow/reference"), { recursive: true });
    mkdirSync(join(cwd, ".kflow/tools"), { recursive: true });
    writeFileSync(join(cwd, "CLAUDE.md"), "Generated by kflow\n");
    writeFileSync(join(cwd, "package.json"), JSON.stringify({ devDependencies: { kflow: "*" } }));

    expect(inspectProjectOnboarding(cwd).health).toEqual({
      structure: "healthy",
      installedPlatforms: "healthy",
      projectCliDependency: "healthy",
      installationEvidence: "consistent",
    });
  });

  it("reports stale authoritative state as missing installation evidence", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [{ name: "claude", installedAt: "2026-07-13T00:00:00.000Z" }],
      version: "2.0.0",
    });

    expect(inspectProjectOnboarding(cwd).health.installationEvidence).toBe("missing");
  });

  it("does not treat a user-owned entry file as kflow installation evidence", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [{ name: "claude", installedAt: "2026-07-13T00:00:00.000Z" }],
      version: "2.0.0",
    });
    writeFileSync(join(cwd, "CLAUDE.md"), "user-owned instructions\n");

    expect(inspectProjectOnboarding(cwd).health.installationEvidence).toBe("missing");
  });

  it("rejects duplicate platforms and empty persisted values", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [
        { name: "codex", installedAt: "2026-07-13T00:00:00.000Z" },
        { name: "codex", installedAt: "" },
      ],
      version: "",
    });

    expect(inspectProjectOnboarding(cwd).installationState.kind).toBe("invalid");
  });

  it("accepts a deterministic filesystem adapter", () => {
    const files = new Map<string, string>([
      ["/project/.kflow/meta.json", JSON.stringify({
        platforms: [{ name: "codex", installedAt: "2026-07-13T00:00:00.000Z" }],
        version: "2.0.0",
      })],
      ["/project/AGENTS.md", "Generated by kflow\n"],
    ]);

    const lifecycle = createProjectOnboardingLifecycle({
      exists: (path) => files.has(path),
      readText: (path) => {
        const text = files.get(path);
        if (text === undefined) throw new Error("missing");
        return text;
      },
    });
    const result = lifecycle.inspect("/project");

    expect(result.installationState.kind).toBe("authoritative");
    expect(result.health.installationEvidence).toBe("consistent");
  });
});
