import { afterEach, describe, expect, it } from "vitest";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tempProject } from "../cli-helpers/temp";
import {
  createProjectOnboardingLifecycle,
  initializeProjectOnboarding,
  inspectProjectOnboarding,
  removeProjectOnboardingPlatforms,
  removeProjectOnboardingAssets,
  synchronizeProjectOnboarding,
} from "../../src/project-onboarding/lifecycle";
import { resolve } from "node:path";

const projects: string[] = [];

function project(): string {
  const cwd = tempProject();
  projects.push(cwd);
  return cwd;
}

function writeMeta(cwd: string, value: unknown): void {
  mkdirSync(join(cwd, ".kflow"), { recursive: true });
  writeFileSync(join(cwd, ".kflow/meta.json"), JSON.stringify(value));
}

afterEach(() => {
  for (const cwd of projects.splice(0)) {
    rmSync(cwd, { recursive: true, force: true });
  }
});

describe("Project Onboarding lifecycle", () => {
  it("removes legacy inferred platform assets without inventing authoritative state", () => {
    const cwd = project();
    writeFileSync(join(cwd, "CLAUDE.md"), "Generated by kflow\n");
    mkdirSync(join(cwd, ".claude/skills/k-flow"), { recursive: true });
    writeFileSync(join(cwd, ".claude/skills/k-flow/SKILL.md"), "legacy skill");

    const result = removeProjectOnboardingPlatforms({ cwd, platforms: ["claude"] });

    expect(result).toMatchObject({
      status: "completed",
      removedPlatforms: ["claude"],
      remainingPlatforms: [],
      warnings: ["legacy-state-not-persisted"],
    });
    expect(existsSync(join(cwd, "CLAUDE.md"))).toBe(false);
    expect(existsSync(join(cwd, ".claude/skills/k-flow"))).toBe(false);
    expect(existsSync(join(cwd, ".kflow/meta.json"))).toBe(false);
  });

  it("does not update Installation State after partial platform-removal failure", () => {
    const metaPath = "/project/.kflow/meta.json";
    const files = new Map<string, string>([
      [metaPath, JSON.stringify({
        platforms: [{ name: "codex", installedAt: "2026-07-13T00:00:00.000Z" }],
        version: "2.0.0",
        ownedSkills: ["k-flow"],
      })],
      ["/project/AGENTS.md", "Generated by kflow\n"],
      ["/project/.agents/skills/k-flow/SKILL.md", "skill"],
    ]);
    const writes: string[] = [];
    const lifecycle = createProjectOnboardingLifecycle({
      exists: (path) => files.has(path) || path === "/project/.agents/skills/k-flow",
      readText: (path) => {
        const text = files.get(path);
        if (text === undefined) throw new Error("missing");
        return text;
      },
      ensureDirectory: () => undefined,
      writeText: (path) => writes.push(path),
      copyDirectory: () => undefined,
      listDirectories: () => [],
      listEntries: () => [],
      removePath: (path) => {
        if (path === "/project/.agents/skills/k-flow") throw new Error("disk full");
        files.delete(path);
      },
    });

    const result = lifecycle.removePlatforms({ cwd: "/project", platforms: ["codex"] });

    expect(result).toMatchObject({
      status: "failed",
      reason: "filesystem-error",
      message: "disk full",
      partialChanges: true,
      completedActions: [{ kind: "entry-file-removed", file: "AGENTS.md" }],
    });
    expect(writes).not.toContain(metaPath);
  });

  it("fully removes kflow assets while preserving non-kflow runtime and entry content", () => {
    const cwd = project();
    const pkgRoot = resolve(import.meta.dirname, "../..");
    initializeProjectOnboarding({
      cwd, pkgRoot, platforms: ["claude", "codex"], version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });
    const userClaudeSkill = join(cwd, ".claude/skills/team-a/SKILL.md");
    const userAgentSkill = join(cwd, ".agents/skills/team-b/SKILL.md");
    mkdirSync(join(cwd, ".claude/skills/team-a"), { recursive: true });
    mkdirSync(join(cwd, ".agents/skills/team-b"), { recursive: true });
    writeFileSync(userClaudeSkill, "team a");
    writeFileSync(userAgentSkill, "team b");
    writeFileSync(join(cwd, "CLAUDE.md"), "user instructions");

    const result = removeProjectOnboardingAssets({ cwd });

    expect(result.status).toBe("completed");
    expect(existsSync(join(cwd, ".kflow"))).toBe(false);
    expect(existsSync(join(cwd, ".claude/skills/k-flow"))).toBe(false);
    expect(existsSync(join(cwd, ".agents/skills/k-flow"))).toBe(false);
    expect(readFileSync(userClaudeSkill, "utf-8")).toBe("team a");
    expect(readFileSync(userAgentSkill, "utf-8")).toBe("team b");
    expect(readFileSync(join(cwd, "CLAUDE.md"), "utf-8")).toBe("user instructions");
    expect(existsSync(join(cwd, "AGENTS.md"))).toBe(false);

    const repeated = removeProjectOnboardingAssets({ cwd });
    expect(repeated).toMatchObject({
      status: "completed",
      projectKnowledgeRemoved: false,
    });
    if (repeated.status === "completed") {
      expect(repeated.actions.filter((action) => action.kind.endsWith("removed"))).toEqual([]);
    }
  });
  it("removes platforms according to shared Runtime Skill Directory and entry-file ownership", () => {
    const cwd = project();
    const pkgRoot = resolve(import.meta.dirname, "../..");
    initializeProjectOnboarding({
      cwd, pkgRoot, platforms: ["codex", "cursor"], version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });
    const customSkill = join(cwd, ".agents/skills/team-skill/SKILL.md");
    mkdirSync(join(cwd, ".agents/skills/team-skill"), { recursive: true });
    writeFileSync(customSkill, "team skill");

    const plan = removeProjectOnboardingPlatforms({ cwd, platforms: ["codex"], apply: false });
    expect(plan).toMatchObject({
      status: "completed",
      actions: expect.arrayContaining([
        { kind: "entry-file-preserved", file: "AGENTS.md", reason: "shared" },
      ]),
    });
    expect(inspectProjectOnboarding(cwd).installationState).toMatchObject({
      platforms: ["codex", "cursor"],
    });

    const first = removeProjectOnboardingPlatforms({ cwd, platforms: ["codex"] });
    expect(first.status).toBe("completed");
    expect(existsSync(join(cwd, "AGENTS.md"))).toBe(true);
    expect(existsSync(join(cwd, ".agents/skills/k-flow/SKILL.md"))).toBe(true);
    expect(inspectProjectOnboarding(cwd).installationState).toMatchObject({ platforms: ["cursor"] });

    const last = removeProjectOnboardingPlatforms({ cwd, platforms: ["cursor"] });
    expect(last.status).toBe("completed");
    expect(existsSync(join(cwd, "AGENTS.md"))).toBe(false);
    expect(existsSync(join(cwd, ".agents/skills/k-flow"))).toBe(false);
    expect(readFileSync(customSkill, "utf-8")).toBe("team skill");
    expect(inspectProjectOnboarding(cwd).installationState).toMatchObject({ platforms: [] });

    const repeated = removeProjectOnboardingPlatforms({ cwd, platforms: ["cursor"] });
    expect(repeated).toMatchObject({ status: "completed", removedPlatforms: [], actions: [] });
  });
  it("synchronizes kflow-owned assets while preserving non-kflow skills and project knowledge", () => {
    const cwd = project();
    const pkgRoot = resolve(import.meta.dirname, "../..");
    initializeProjectOnboarding({
      cwd, pkgRoot, platforms: ["claude", "codex"], version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });
    const staleSkillFile = join(cwd, ".agents/skills/k-flow/stale.md");
    const customSkill = join(cwd, ".agents/skills/team-skill/SKILL.md");
    const projectKnowledge = join(cwd, ".kflow/features/my-feature.md");
    const corruptedClaudeSkill = join(cwd, ".claude/skills/k-flow/SKILL.md");
    const staleReference = join(cwd, ".kflow/reference/stale.md");
    const staleTool = join(cwd, ".kflow/tools/stale.py");
    writeFileSync(staleSkillFile, "stale");
    mkdirSync(join(cwd, ".agents/skills/team-skill"), { recursive: true });
    writeFileSync(customSkill, "team skill");
    writeFileSync(projectKnowledge, "project knowledge");
    writeFileSync(corruptedClaudeSkill, "corrupted");
    writeFileSync(staleReference, "stale");
    writeFileSync(staleTool, "stale");

    const result = synchronizeProjectOnboarding({ cwd, pkgRoot });
    const repeated = synchronizeProjectOnboarding({ cwd, pkgRoot });

    expect(result.status).toBe("completed");
    expect(repeated.status).toBe("completed");
    expect(existsSync(staleSkillFile)).toBe(false);
    expect(readFileSync(customSkill, "utf-8")).toBe("team skill");
    expect(readFileSync(projectKnowledge, "utf-8")).toBe("project knowledge");
    expect(readFileSync(corruptedClaudeSkill, "utf-8")).not.toBe("corrupted");
    expect(existsSync(staleReference)).toBe(false);
    expect(existsSync(staleTool)).toBe(false);
  });

  it("deduplicates Runtime Skill Directories from authoritative Installation State", () => {
    const files = new Map<string, string>([
      ["/project/.kflow/meta.json", JSON.stringify({
        platforms: [
          { name: "claude", installedAt: "2026-07-13T00:00:00.000Z" },
          { name: "codex", installedAt: "2026-07-13T00:00:00.000Z" },
          { name: "cursor", installedAt: "2026-07-13T00:00:00.000Z" },
        ],
        version: "2.0.0",
      })],
      ["/project/CLAUDE.md", "Generated by kflow\n"],
      ["/project/AGENTS.md", "Generated by kflow\n"],
    ]);
    const copies: string[] = [];
    const lifecycle = createProjectOnboardingLifecycle({
      exists: (path) => files.has(path),
      readText: (path) => {
        const value = files.get(path);
        if (value === undefined) throw new Error("missing");
        return value;
      },
      ensureDirectory: () => undefined,
      writeText: (path, value) => files.set(path, value),
      copyDirectory: (_source, destination) => copies.push(destination),
      listDirectories: () => ["k-flow"],
      listEntries: () => ["k-flow"],
      removePath: () => undefined,
    });

    const result = lifecycle.synchronize({ cwd: "/project", pkgRoot: "/package" });

    expect(result).toMatchObject({
      status: "completed",
      runtimeSkillDirectories: [".claude/skills", ".agents/skills"],
      warnings: [],
    });
    expect(copies.filter((path) => path.endsWith("/k-flow"))).toEqual([
      "/project/.claude/skills/k-flow",
      "/project/.agents/skills/k-flow",
    ]);
  });

  it("removes packaged skills deleted or renamed upstream without removing user skills", () => {
    const files = new Map<string, string>([
      ["/project/.kflow/meta.json", JSON.stringify({
        platforms: [{ name: "codex", installedAt: "2026-07-13T00:00:00.000Z" }],
        version: "2.0.0",
      })],
      ["/project/AGENTS.md", "Generated by kflow\n"],
    ]);
    const removed: string[] = [];
    const lifecycle = createProjectOnboardingLifecycle({
      exists: (path) => files.has(path),
      readText: (path) => {
        const value = files.get(path);
        if (value === undefined) throw new Error("missing");
        return value;
      },
      ensureDirectory: () => undefined,
      writeText: (path, value) => files.set(path, value),
      copyDirectory: () => undefined,
      listDirectories: () => ["k-flow"],
      listEntries: () => ["k-flow"],
      removePath: (path) => removed.push(path),
    });

    const result = lifecycle.synchronize({ cwd: "/project", pkgRoot: "/package" });

    expect(result.status).toBe("completed");
    expect(removed).toContain("/project/.agents/skills/k-onboard");
    expect(removed).not.toContain("/project/.agents/skills/team-skill");
    expect(files.get("/project/.kflow/meta.json")).toContain('"ownedSkills": [\n    "k-flow"');
  });

  it("blocks synchronization when persisted skill ownership can escape its Runtime Skill Directory", () => {
    const removed: string[] = [];
    const lifecycle = createProjectOnboardingLifecycle({
      exists: (path) => path === "/project/.kflow/meta.json",
      readText: () => JSON.stringify({
        platforms: [{ name: "codex", installedAt: "2026-07-13T00:00:00.000Z" }],
        version: "2.0.0",
        ownedSkills: ["../../team-owned"],
      }),
      ensureDirectory: () => undefined,
      writeText: () => undefined,
      copyDirectory: () => undefined,
      listDirectories: () => ["k-flow"],
      listEntries: () => ["k-flow"],
      removePath: (path) => removed.push(path),
    });

    expect(lifecycle.synchronize({ cwd: "/project", pkgRoot: "/package" })).toEqual({
      status: "blocked",
      reason: "unsafe-installation-state",
      installationState: "invalid",
    });
    expect(removed).toEqual([]);
  });

  it("uses an explicit universal-runtime fallback when legacy state is absent", () => {
    const copies: string[] = [];
    const lifecycle = createProjectOnboardingLifecycle({
      exists: () => false,
      readText: () => { throw new Error("missing"); },
      ensureDirectory: () => undefined,
      writeText: () => undefined,
      copyDirectory: (_source, destination) => copies.push(destination),
      listDirectories: () => ["k-flow"],
      listEntries: () => ["k-flow"],
      removePath: () => undefined,
    });

    const result = lifecycle.synchronize({ cwd: "/project", pkgRoot: "/package" });

    expect(result).toMatchObject({
      status: "completed",
      runtimeSkillDirectories: [".agents/skills"],
      warnings: ["legacy-default-runtime"],
    });
  });

  it("is idempotent for universal-only, Claude-only, and mixed installations", () => {
    const pkgRoot = resolve(import.meta.dirname, "../..");
    for (const platforms of [["codex"], ["claude"], ["claude", "codex"]] as const) {
      const cwd = project();
      initializeProjectOnboarding({
        cwd,
        pkgRoot,
        platforms: [...platforms],
        version: "2.0.0",
        installedAt: "2026-07-13T00:00:00.000Z",
      });

      expect(synchronizeProjectOnboarding({ cwd, pkgRoot }).status).toBe("completed");
      expect(synchronizeProjectOnboarding({ cwd, pkgRoot }).status).toBe("completed");
      if (platforms.includes("claude")) {
        expect(existsSync(join(cwd, ".claude/skills/k-flow/SKILL.md"))).toBe(true);
      }
      if (platforms.includes("codex")) {
        expect(existsSync(join(cwd, ".agents/skills/k-flow/SKILL.md"))).toBe(true);
      }
    }
  });
  it("initializes selected platforms through one lifecycle interface", () => {
    const cwd = project();
    const pkgRoot = resolve(import.meta.dirname, "../..");

    const result = initializeProjectOnboarding({
      cwd,
      pkgRoot,
      platforms: ["claude", "codex"],
      version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });

    expect(result.runtimeSkillDirectories).toEqual([".claude/skills", ".agents/skills"]);
    expect(result.installedPlatforms).toEqual(["claude", "codex"]);
    expect(readFileSync(join(cwd, ".kflow/meta.json"), "utf-8")).toContain('"version": "2.0.0"');
    expect(existsSync(join(cwd, ".claude/skills/k-flow/SKILL.md"))).toBe(true);
    expect(existsSync(join(cwd, ".agents/skills/k-flow/SKILL.md"))).toBe(true);
    expect(existsSync(join(cwd, "CLAUDE.md"))).toBe(true);
    expect(existsSync(join(cwd, "AGENTS.md"))).toBe(true);
  });

  it("keeps existing Installation State stable when initialization is repeated", () => {
    const cwd = project();
    const pkgRoot = resolve(import.meta.dirname, "../..");
    initializeProjectOnboarding({
      cwd, pkgRoot, platforms: ["codex"], version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });

    initializeProjectOnboarding({
      cwd, pkgRoot, platforms: ["codex"], version: "2.0.0",
      installedAt: "2026-07-14T00:00:00.000Z",
    });

    const meta = JSON.parse(readFileSync(join(cwd, ".kflow/meta.json"), "utf-8"));
    expect(meta.platforms).toEqual([
      { name: "codex", installedAt: "2026-07-13T00:00:00.000Z" },
    ]);
  });

  it("promotes inferred legacy platforms into complete authoritative Installation State", () => {
    const cwd = project();
    const pkgRoot = resolve(import.meta.dirname, "../..");
    writeFileSync(join(cwd, "CLAUDE.md"), "Generated by kflow\n");

    const result = initializeProjectOnboarding({
      cwd, pkgRoot, platforms: ["codex"], version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });

    expect(result.status).toBe("completed");
    const meta = JSON.parse(readFileSync(join(cwd, ".kflow/meta.json"), "utf-8"));
    expect(meta.platforms.map((entry: { name: string }) => entry.name)).toEqual(["claude", "codex"]);
  });

  it("blocks initialization before writes when authoritative state is malformed", () => {
    const cwd = project();
    const pkgRoot = resolve(import.meta.dirname, "../..");
    mkdirSync(join(cwd, ".kflow"), { recursive: true });
    writeFileSync(join(cwd, ".kflow/meta.json"), "{not-json");

    const result = initializeProjectOnboarding({
      cwd, pkgRoot, platforms: ["codex"], version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });

    expect(result).toEqual({
      status: "blocked",
      reason: "unsafe-installation-state",
      installationState: "malformed",
    });
    expect(readFileSync(join(cwd, ".kflow/meta.json"), "utf-8")).toBe("{not-json");
    expect(existsSync(join(cwd, ".agents"))).toBe(false);
  });
  it("treats valid persisted Installation State as authoritative over entry files", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [{ name: "claude", installedAt: "2026-07-13T00:00:00.000Z" }],
      version: "2.0.0",
    });
    writeFileSync(join(cwd, "AGENTS.md"), "Generated by kflow\n");

    const result = inspectProjectOnboarding(cwd);

    expect(result.installationState).toEqual({
      kind: "authoritative",
      platforms: ["claude"],
      version: "2.0.0",
      ownedSkills: expect.arrayContaining(["k-flow", "k-onboard"]),
    });
  });

  it("distinguishes malformed persisted Installation State from absent state", () => {
    const cwd = project();
    mkdirSync(join(cwd, ".kflow"), { recursive: true });
    writeFileSync(join(cwd, ".kflow/meta.json"), "{not-json");

    const result = inspectProjectOnboarding(cwd);

    expect(result.installationState).toEqual({
      kind: "malformed",
      reason: "invalid-json",
    });
  });

  it("reports structurally invalid persisted Installation State", () => {
    const cwd = project();
    writeMeta(cwd, { platforms: [{ name: "unknown" }], version: 2 });

    expect(inspectProjectOnboarding(cwd).installationState).toEqual({
      kind: "invalid",
      reason: "invalid-shape",
    });
  });

  it("reports absent Installation State when no persisted or legacy evidence exists", () => {
    expect(inspectProjectOnboarding(project()).installationState).toEqual({ kind: "absent" });
  });

  it("infers legacy Installation State only when persisted state is absent", () => {
    const cwd = project();
    writeFileSync(join(cwd, "CLAUDE.md"), "Generated by kflow\n");

    expect(inspectProjectOnboarding(cwd).installationState).toEqual({
      kind: "inferred",
      platforms: ["claude"],
    });
  });

  it("reports all candidates represented by the shared legacy entry file", () => {
    const cwd = project();
    writeFileSync(join(cwd, "AGENTS.md"), "Generated by kflow\n");

    expect(inspectProjectOnboarding(cwd).installationState).toEqual({
      kind: "inferred",
      platforms: ["codex", "cursor", "opencode"],
    });
  });

  it("returns structured health facts from the same Installation State", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [{ name: "claude", installedAt: "2026-07-13T00:00:00.000Z" }],
      version: "2.0.0",
    });
    mkdirSync(join(cwd, ".kflow/reference"), { recursive: true });
    mkdirSync(join(cwd, ".kflow/tools"), { recursive: true });
    writeFileSync(join(cwd, "CLAUDE.md"), "Generated by kflow\n");
    writeFileSync(join(cwd, "package.json"), JSON.stringify({ devDependencies: { kflow: "*" } }));

    expect(inspectProjectOnboarding(cwd).health).toEqual({
      structure: "healthy",
      installedPlatforms: "healthy",
      projectCliDependency: "healthy",
      installationEvidence: "consistent",
    });
  });

  it("reports stale authoritative state as missing installation evidence", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [{ name: "claude", installedAt: "2026-07-13T00:00:00.000Z" }],
      version: "2.0.0",
    });

    expect(inspectProjectOnboarding(cwd).health.installationEvidence).toBe("missing");
  });

  it("does not treat a user-owned entry file as kflow installation evidence", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [{ name: "claude", installedAt: "2026-07-13T00:00:00.000Z" }],
      version: "2.0.0",
    });
    writeFileSync(join(cwd, "CLAUDE.md"), "user-owned instructions\n");

    expect(inspectProjectOnboarding(cwd).health.installationEvidence).toBe("missing");
  });

  it("rejects duplicate platforms and empty persisted values", () => {
    const cwd = project();
    writeMeta(cwd, {
      platforms: [
        { name: "codex", installedAt: "2026-07-13T00:00:00.000Z" },
        { name: "codex", installedAt: "" },
      ],
      version: "",
    });

    expect(inspectProjectOnboarding(cwd).installationState.kind).toBe("invalid");
  });

  it("accepts a deterministic filesystem adapter", () => {
    const files = new Map<string, string>([
      ["/project/.kflow/meta.json", JSON.stringify({
        platforms: [{ name: "codex", installedAt: "2026-07-13T00:00:00.000Z" }],
        version: "2.0.0",
      })],
      ["/project/AGENTS.md", "Generated by kflow\n"],
    ]);

    const copied: string[] = [];
    const lifecycle = createProjectOnboardingLifecycle({
      exists: (path) => files.has(path),
      readText: (path) => {
        const text = files.get(path);
        if (text === undefined) throw new Error("missing");
        return text;
      },
      ensureDirectory: () => undefined,
      writeText: (path, text) => files.set(path, text),
      copyDirectory: (_source, destination) => copied.push(destination),
      listDirectories: () => [],
      listEntries: () => [],
      removePath: () => undefined,
    });
    const result = lifecycle.inspect("/project");

    expect(result.installationState.kind).toBe("authoritative");
    expect(result.health.installationEvidence).toBe("consistent");

    const initialized = lifecycle.initialize({
      cwd: "/next",
      pkgRoot: "/package",
      platforms: ["codex", "cursor"],
      version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });
    expect(initialized.runtimeSkillDirectories).toEqual([".agents/skills"]);
    expect(copied.filter((path) => path === "/next/.agents/skills")).toHaveLength(1);
  });

  it("returns structured partial actions when initialization filesystem work fails", () => {
    const copied: string[] = [];
    const lifecycle = createProjectOnboardingLifecycle({
      exists: () => false,
      readText: () => { throw new Error("missing"); },
      ensureDirectory: () => undefined,
      writeText: () => undefined,
      copyDirectory: (_source, destination) => {
        copied.push(destination);
        if (destination === "/project") throw new Error("disk full");
      },
      listDirectories: () => [],
      listEntries: () => [],
      removePath: () => undefined,
    });

    const result = lifecycle.initialize({
      cwd: "/project",
      pkgRoot: "/package",
      platforms: ["codex"],
      version: "2.0.0",
      installedAt: "2026-07-13T00:00:00.000Z",
    });

    expect(result).toMatchObject({
      status: "failed",
      reason: "filesystem-error",
      message: "disk full",
      partialChanges: true,
      completedActions: [
        { kind: "runtime-skills-installed", directory: ".agents/skills" },
      ],
    });
  });
});
